framework:
    asset_mapper:
        # you could choose get CDN urls from a different source
        # provider: 'jsdelivr'
        paths:
#            - assets
            # the more complex config format with namespaced paths
            'assets/': ''
            'custom_assets': 'custom'
